version: '3'
services:

  mongodb:
    image: mongo
    container_name: my_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  redis:
      image: redis:alpine3.20
      container_name: redis_cache_server
      ports:
        - "6379:6379"

  nginx:
    image: nginx:alpine3
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "3000:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

volumes:
  mongodb_data:
    driver: local