version: '3.8'
services:

  mongodb:
    image: mongo
    container_name: mongo_db_server_prod
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./common/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  redis:
      image: redis:alpine3.20
      container_name: redis_cache_server_dev
      ports:
        - "6379:6379"

  nginx:
    image: nginx:stable
    container_name: nginx_dev
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "443:443"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

volumes:
  mongodb_data:
    driver: local