version: '3'
services:

  mongodb:
    image: mongo
    container_name: my_mongodb_prod
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./common/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  redis:
      image: redis:alpine3.20
      container_name: redis_cache_server_prod
      ports:
        - "6379:6379"

  nginx:
    image: nginx:alpine3
    container_name: nginx_prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "3000:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  main_service:
    build: ./main_service
    ports: 
      - "3001:3000"
    depends_on:
      - mongodb
      - redis
    container_name: main_service
    env_file:
      - ./main/.env
    
  auth_service:
    build: ./auth_service
    ports: 
      - "3002:3000"
    depends_on:
      - mongodb
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    container_name: auth_service
    env_file:
      - ./auth/.env

volumes:
  mongodb_data:
    driver: local